tasks:
  - init: |
      gp open README.md
      wget -q https://raw.githubusercontent.com/dapr/cli/master/install/install.sh -O - | DAPR_INSTALL_DIR="$HOME/dapr" /bin/bash
      # create an alias to run dapr using the shortcut dapr
      alias dapr="/home/gitpod/dapr/dapr"
      dapr -v
      # initialize dapr - see https://docs.dapr.io/getting-started/install-dapr-selfhost/ 
      dapr init
      dapr --version
      # container instances with daprio/dapr, openzipkin/zipkin, and redis images should be running:
      docker ps


